
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label label1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textMain;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TreeView treeViewUsers;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button buttonStep;

	private global::Gtk.Button buttonPlay;

	private global::Gtk.Button buttonExit;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Radical PuppetMaster");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("One legendary gui... logs and stuff");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textMain = new global::Gtk.TextView ();
		this.textMain.Buffer.Text = "Loading...";
		this.textMain.CanFocus = true;
		this.textMain.Name = "textMain";
		this.textMain.Editable = false;
		this.textMain.WrapMode = ((global::Gtk.WrapMode)(2));
		this.textMain.Indent = 2;
		this.GtkScrolledWindow.Add (this.textMain);
		this.hbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
		w3.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.treeViewUsers = new global::Gtk.TreeView ();
		this.treeViewUsers.CanFocus = true;
		this.treeViewUsers.Name = "treeViewUsers";
		this.GtkScrolledWindow1.Add (this.treeViewUsers);
		this.hbox2.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow1]));
		w5.Position = 1;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w6.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonStep = new global::Gtk.Button ();
		this.buttonStep.CanFocus = true;
		this.buttonStep.Name = "buttonStep";
		this.buttonStep.UseUnderline = true;
		this.buttonStep.Label = "Step";
		this.hbox1.Add (this.buttonStep);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonStep]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonPlay = new global::Gtk.Button ();
		this.buttonPlay.CanFocus = true;
		this.buttonPlay.Name = "buttonPlay";
		this.buttonPlay.UseUnderline = true;
		this.buttonPlay.Label = global::Mono.Unix.Catalog.GetString ("Play");
		this.hbox1.Add (this.buttonPlay);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonPlay]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		w8.Padding = ((uint)(5));
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonExit = new global::Gtk.Button ();
		this.buttonExit.CanFocus = true;
		this.buttonExit.Name = "buttonExit";
		this.buttonExit.UseUnderline = true;
		this.buttonExit.Label = global::Mono.Unix.Catalog.GetString ("Exit");
		this.hbox1.Add (this.buttonExit);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonExit]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonStep.Clicked += new global::System.EventHandler (this.OnButtonStepClicked);
		this.buttonPlay.Clicked += new global::System.EventHandler (this.OnButtonPlayClicked);
		this.buttonExit.Clicked += new global::System.EventHandler (this.OnButtonExitClicked);
	}
}
